### ISSUE TITLE
verbose output for `poetry poly sync`

### ISSUE THREAD

**Issue by Panaetius** [DavidVujic/python-polylith#101]
**Is your feature request related to a problem? Please describe.**
I just spent quite some time figuring out why `poetry poly sync` was adding dependencies of `project_a` to `project_b` even though `project_b` should not depend on them. The issue was in code, but `poetry poly sync` doesn't give any help in figuring out where a dependency is coming from. `-vvv` doesn't print anything more than without the verbose flag.

**Describe the solution you'd like**
It'd be nice if `-v` on `poetry poly sync` could print where a dependency is coming from. Alternatively `poetry poly check` could show this information. Pretty-printing `brick_imports` would probably already be enough.
As a start, it'd already help to just know what component a dependency is coming from. It'd be awesome if it could show code locations as well.

**Additional context**
For a bit more context, in code there was a `migrations` component that contains alembic migrations code. There is general migrations code, that doesn't depend on anything, and then different `x_migrations` subdirectories for migrations of different other components. The individual migrations depend on the components in question, but the generic migrations code does not. The individual migrations folder also don't contain an `__init__.py`, so they're not exported with the component itself, only referenced in alembic.ini configuration. So there actually was no direct dependency on the code in question. But since poetry poly uses `glob('*.py')`, it still found the python files and calculated imports from there. This made debugging the issue harder.

That component looks like
```
|- __init__.py
|- alembic.ini
|- core.py
|- env.py 
L_ a_migrations
  L_ migrations
    |- __init__.py
    |- env.py   <-- this depends on a component only needed for project_a
    L_ versions
        |- <migrationsfile>.py
```
I didn't want to break this up into further components to not clutter the hierarchy more than needed, and didn't expect poly to pick up on the env.py in the subfolder (since there's no `__init__.py`).

But I don't think this necessarily needs to be changed, technically the migrations subfolder code does depend on the project_a component. Though it is more of an indirect dependency. I wonder if having a way to ignore a dependency with something like a `# poly: ignore-import` comment, could be a helpful addition as well. It might help in some cases when migrating from non-polylith code to polylith.

**Comment by DavidVujic** [comment]
Thank you for reporting this @Panaetius! I agree, the `sync` & `check` commands should have a verbose option. I'll look into it.

**Comment by DavidVujic** [comment]
The `sync` and `check` commands now have basic support for verbose output:

![poly-check-sync-verbose](https://github.com/DavidVujic/python-polylith/assets/301286/35515222-eacf-4fb8-8766-3955536dde1e)

**Comment by Panaetius** [comment]
Thank you very much! :pray:
