### ISSUE TITLE
Sync should respect --quiet flag

### ISSUE THREAD

**Issue by BeRT2me** [DavidVujic/python-polylith#109]
**Describe the bug**
`poetry poly sync --quiet` should not have any output.

**To Reproduce**
1. Open a terminal window 
2. Go to root of the project
4. Run the command `poetry poly sync --quiet`
5. See output where there should be none.

**Expected behavior**
`poetry poly sync --quiet` should have no output.

**Additional context**
It doesn't appear that `--quiet` is respected by any `poetry poly` command, but to me `sync` is one of the most likely scenarios where someone would want this functionality.

**Comment by DavidVujic** [comment]
Thank you for reporting @BeRT2me! 👏  

I totally agree, `--quiet` should be respected by the poly tool. I will have a look at this during next week.
