### ISSUE TITLE
poly diff reports changes on non-brick code

### ISSUE THREAD

**Issue by DavidVujic** [DavidVujic/python-polylith#125]
**Describe the bug**
The `test` folder (when structured in the same way as the bricks) is reported as changed in the view when running `poetry poly diff`.

This can be confusing, since it is not a brick that is used in the projects.

**To Reproduce**
1. Make changes in a unit test.
2. Run `poetry poly diff`
3. the  `test` folder is reported in the table view.

**Expected behavior**
The `poly diff` command should only highlight changes in bricks and map them to usage in the projects.

**Comment by davzucky** [comment]
@DavidVujic We have the opposite problem. We want to optimize our CI for changes; however, sometimes, the change is only related to the tests. Could we have a flag to say include test ?

**Comment by DavidVujic** [comment]
@davzucky Good idea! I'll think about it. The poly tool should have better test support.

Meanwhile, would this work for you?

```bash
# assuming the test folder is named "test/"

git diff <your-tag-name> --stat --name-only test/
```

This should return a list of all changed files within that folder and compared to a certain git tag.

**Comment by davzucky** [comment]
Thank you for coming back to me.
I think this could work. However, it won't attach to the proper project.
We are using GitLab and creating a GitLab subpipeline using `poly diff` to run only for the projects that have changed. This means it happened before we ran the test.
This is not a blocker. However, it would be nice to include them as well in the test and get them attached to the right project.

**Comment by DavidVujic** [comment]
To help me understand the problem: from a test that has changed, what information would you want to have?

**Comment by DavidVujic** [comment]
@davzucky I just realized that I have a lot of the ground work in place already.

I'm thinking about a feature that can analyze the tests, and report on which bricks and projects they touch. I think it also could identify the relevant bricks and projects for a changed test. This command (or commands) could have its corresponding CI-friendly version with output that can be used programmatically (in similar way as `poly diff --short`).

Right now, it doesn't feel like a huge task to complete. But maybe I will learn more as the work proceeds 😄 

I feel inspired to do some work on this, thank you for sharing your ideas 💡

**Comment by davzucky** [comment]
@DavidVujic, I'm sorry for the delay. I'm happy to know that motivates you. Yes, this is precisely what we would like. When we create new `components` or `bases,` Poly creates the equivalent test. I expect you can have a map of 1-1.

Looking forward to get that.

**Comment by DavidVujic** [comment]
@davzucky I haven't been able to work on this until recently, and today I have deployed a new version of the CLI and the Poetry plugin.

Announcement here, introducing a new `poly test` command and I would love to hear your feedback about it!

https://github.com/DavidVujic/python-polylith/discussions/332
