### ISSUE TITLE
Support for different git tag patterns (stable-*, release-* etc.)

### ISSUE THREAD

**Issue by licht1stein** [DavidVujic/python-polylith#130]
It would be great to be able to add multiple git tag patterns and check for changes since each of then (like "release-*" tag). At the moment I have 6 docker images recompiling and pushing to repo on each change. Something like this would let me only compile what changed since last release:

Maybe instead of this:

```yml
[tool.polylith]
namespace = "ufy"
git_tag_pattern = "stable-*"
```

We could have:

```yml
[tool.polylith.git_tag_patterns]
stable="stable-*"
release="release-[0-9][0-9][0-9][0-9]-*"
```
And then have `poetry poly diff --since release`?

This can even be a non-breaking change. The user can still use git_tag_pattern but adding the separate section would override it.

**Comment by DavidVujic** [comment]
Great idea! I agree, this would be very helpful and can also be added as a non-breaking release. I'll have a look at it 😄
