### ISSUE TITLE
there are some errors using rye

### ISSUE THREAD

**Issue by markqiu** [DavidVujic/python-polylith#192]
raise FileNotFoundError(msg)
FileNotFoundError: Forced include not found: /private/var/folders/rc/m01mh1mn3m99t4879pf_wbk40000gn/T/build-via-sdist-fpf28p9w/profitcube-0.1.0/components/profitcube/abilities

ERROR Backend subprocess exited when trying to invoke build_wheel

Could you please help me, thank you!

**Comment by DavidVujic** [comment]
Hi @markqiu!

Do you have a pyproject.toml for the project that fails to share?

You can leave out any data that is not allowed to show in public if you want. What I am most interested in is the `build-system` section and the `tool.hatch` and `tool.polylith` sections.

I ran a fresh install of Rye, and tested it out with [the example Rye repo](https://github.com/DavidVujic/python-polylith-example-rye) to build wheels and couldn't reproduce any errors.

**Comment by markqiu** [comment]
```toml
[project]
name = "profitcube"
version = "0.1.0"
description = "jinniuai's investment power store"
authors = [
    { name = "markqiu", email = "qiucheng@jinniuai.com" }
]
dependencies = [
    "jinja2>=3.1.3",
    "typer>=0.12.2",
    "rich>=13.7.1",
    "numpy>=1.26.4",
    "pydantic>=2.6.4",
    "loguru>=0.7.2",
    "pandas>=2.2.1",
    "pandera>=0.18.3",
    "dolphindb>=3.0.0.0",
    "mootdx>=0.11.4",
    "openpyxl>=3.1.2",
    "mytt>=2.9.3",
    "python-dotenv>=1.0.1",
    "simple-toml-configurator>=1.2.2",
    "croniter>=2.0.3",
    "statsmodels>=0.14.1",
]
readme = "README.md"
requires-python = ">= 3.11"

[build-system]
requires = ["hatchling", "hatch-polylith-bricks"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "polylith-cli",
]

[tool.hatch.build]
dev-mode-dirs = ["components", "bases", "development", "."]

[tool.hatch.build.hooks.polylith-bricks]


[tool.polylith.bricks]
"bases/profitcube/cli" = "profitcube/cli"
"bases/profitcube/config" = "profitcube/config"
"components/profitcube/core" = "profitcube/core"
"components/profitcube/abilities" = "profitcube/abilities"
"components/profitcube/backtest" = "profitcube/backtest"
"components/profitcube/resources" = "profitcube/resources"
"components/profitcube/utils" = "profitcube/utils"
"components/profitcube/data" = "profitcube/data"
"components/profitcube/可视化" = "profitcube/可视化"

[tool.hatch.metadata]
allow-direct-references = true

[tool.ruff]
exclude = [
  ".git",
  ".github",
  "__pycache__",
  ".mypy_cache",
  ".ruff_cache",
  "dist",
  ".venv",
  "./development/*.py",
]
line-length = 120

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]

```

which produces the following error:
```txt
          polylith-cli==1.1.2
          polylith-cli==1.2.0
          polylith-cli==1.2.1
          polylith-cli==1.3.0
          polylith-cli==1.4.0
          polylith-cli==1.4.1
          polylith-cli==1.5.0
      we can conclude that all versions of polylith-cli depend on typer>=0.9.0,<0.10.0.
      And because you require typer>=0.12.2 and you require polylith-cli, we can conclude that the requirements are unsatisfiable.
error: could not write dev lockfile for project

Caused by:
```

**Comment by DavidVujic** [comment]
Thank tou @markqiu !

It could be because the polylith CLI has set the Typer dependency wrong, and Rye not being able to resolve this conflict.

I will look into it!

**Comment by DavidVujic** [comment]
@markqiu 

I think I have been able to reproduce this error. 

Running `rye build` will fail according to your output.

But running `rye build --wheel` and/or `rye build --sdist` works fine. I am not sure if this is Polylith-related or not. But will investigate it further. I would recommend to run the build command with the options to make this thing work well.

**Comment by DavidVujic** [comment]
I will update that one too, sorry for the inconvenience 🙏 

I think that I had set that version because of Poetry, but this can be done in a better way, I realize now. I will have a look at it.

**Comment by DavidVujic** [comment]
Hopefully I have solved this new issue now 😄 

There's a new version of the CLI and also the hatch build hook available.

**Comment by markqiu** [comment]
The new issue has been solved!
Thank you very much.
