### ISSUE TITLE
"poetry poly sync" returns "'Key "tool" does not exist.|

### ISSUE THREAD

**Issue by ZaighumRajput** [DavidVujic/python-polylith#215]
All commands except for "poetry poly deps" return "'Key "tool" does not exist". 
I am not entirely sure what changed. It had been working fine for a while.
I am sure it is an issue with the configuration of my current project because creating an empty project works fine. 
Any tips on how to debug further would be greatly appreciated. Thank you kindly!

poetry --version
Poetry (version 1.8.3)
Python (3.11.9)
OS Windows 11

![image](https://github.com/DavidVujic/python-polylith/assets/4844398/1f28bcc2-dcee-492a-b6d9-08504006138f)

.\ workspace.toml
[tool.polylith]
namespace = "toolkit"
git_tag_pattern = "stable-*"

[tool.polylith.structure]
theme = "loose"

[tool.polylith.tag.patterns]
stable = "stable-*"
release = "v[0-9]*"

[tool.polylith.resources]
brick_docs_enabled = false

[tool.polylith.test]
enabled = true

**Comment by ZaighumRajput** [comment]
`poetry poly check -vvv

  Stack trace:

  14  ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\cleo\application.py:327 in run
       325│
       326│             try:
     → 327│                 exit_code = self._run(io)
       328│             except BrokenPipeError:
       329│                 # If we are piped to another process, it may close early and send a

  13  ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\poetry\console\application.py:190 in _run
       188│         self._load_plugins(io)
       189│
     → 190│         exit_code: int = super()._run(io)
       191│         return exit_code
       192│

  12  ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\cleo\application.py:431 in _run
       429│             io.input.interactive(interactive)
       430│
     → 431│         exit_code = self._run_command(command, io)
       432│         self._running_command = None
       433│

  11  ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\cleo\application.py:473 in _run_command
       471│
       472│         if error is not None:
     → 473│             raise error
       474│
       475│         return terminate_event.exit_code

  10  ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\cleo\application.py:457 in _run_command
       455│
       456│             if command_event.command_should_run():
     → 457│                 exit_code = command.run(io)
       458│             else:
       459│                 exit_code = ConsoleCommandEvent.RETURN_CODE_DISABLED

   9  ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\cleo\commands\base_command.py:117 in run
       115│         io.input.validate()
       116│
     → 117│         return self.execute(io) or 0
       118│
       119│     def merge_application_definition(self, merge_args: bool = True) -> None:

   8  ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\cleo\commands\command.py:61 in execute
        59│
        60│         try:
     →  61│             return self.handle()
        62│         except KeyboardInterrupt:
        63│             return 1

   7  ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\polylith\poetry\commands\check.py:57 in handle
        55│         ns = configuration.get_namespace_from_config(root)
        56│
     →  57│         all_projects_data = info.get_projects_data(root, ns)
        58│         only_projects_data = [p for p in all_projects_data if info.is_project(p)]
        59│

   6  ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\polylith\info\collect.py:55 in get_projects_data
        53│     components = get_components(root, ns)
        54│
     →  55│     return get_bricks_in_projects(root, components, bases, ns)
        56│

   5  ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\polylith\info\collect.py:38 in get_bricks_in_projects
        36│     root: Path, components: List[str], bases: List[str], namespace: str
        37│ ) -> List[dict]:
     →  38│     packages_for_projects = get_packages_for_projects(root)
        39│
        40│     res = [

   4  ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\polylith\project\get.py:48 in get_packages_for_projects
        46│     namespace = configuration.get_namespace_from_config(root)
        47│
     →  48│     return [
        49│         {
        50│             "name": get_project_name(d["toml"]),

   3  ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\polylith\project\get.py:50 in <listcomp>
        48│     return [
        49│         {
     →  50│             "name": get_project_name(d["toml"]),
        51│             "packages": toml.get_project_package_includes(namespace, d["toml"]),
        52│             "path": d["path"],

   2  ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\polylith\project\get.py:13 in get_project_name
        11│         return data["project"]["name"]
        12│
     →  13│     return data["tool"]["poetry"]["name"]
        14│
        15│

   1  ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\tomlkit\container.py:624 in __getitem__
       622│     # Dictionary methods
       623│     def __getitem__(self, key: Key | str) -> Item | Container:
     → 624│         item = self.item(key)
       625│         if isinstance(item, Item) and item.is_boolean():
       626│             return item.value

  NonExistentKey

  'Key "tool" does not exist.'

  at ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\tomlkit\container.py:466 in item
      462│             key = SingleKey(key)
      463│
      464│         idx = self._map.get(key)
      465│         if idx is None:
    → 466│             raise NonExistentKey(key)
      467│
      468│         if isinstance(idx, tuple):
      469│             # The item we are getting is an out of order table
      470│             # so we need a proxy to retrieve the proper objects
PS >
`

**Comment by ZaighumRajput** [comment]
Actually, it seems to have been caused by having a sub directroy in the ./projects/ folder.
Removing it helped, though I cannot confirm.

**Comment by DavidVujic** [comment]
Hi @ZaighumRajput! Great that you have solved the issue 👏 

I am curious about what caused it. I tried with adding a subfolder to projects, but couldn't reproduce the error. Do you have any more info on what might have been the reason? Did the subfolder contain a pyproject.toml file?

**Comment by DavidVujic** [comment]
Update:

I think I know what might have caused it: a project sub-folder, containing a `pyproject.toml` file that is empty or missing `[tool.poetry]`. That will result in a `KeyError` raised from Poetry (internally from the library `cleo`).

Is that what happened? @ZaighumRajput

**Comment by gazzar** [comment]
Hi @DavidVujic

I tripped over this problem today in one of my venvs, which led me to this (now closed) issue.
I'm using poetry with local venvs and when this error occurred I updated to the latest version of polylith with your more verbose output. The error I get now is:
'Error in /home/rubeng/projects/xfm-stack/projects/xfm_jupyter/.venv/lib/python3.11/site-packages/jupyterlab/tests/mock_packages/test-hyphens'

So the problematic pyproject.toml file, which indeed doesn't contain a [tool.poetry] section, is actually installed in the local .venv associated with my xfm_jupyter project, which causes the problem because it includes jupyterlab.
You can see the pyproject file here:
https://github.com/jupyterlab/jupyterlab/blob/main/jupyterlab/tests/mock_packages/test-hyphens/pyproject.toml

I'm not sure that python-polylith should be traversing down into a local .venv. Presumably other packages other than jupyterlab could also install their own pyproject.toml file in a .venv within the polylith file tree and they should be ignored too.

**Comment by DavidVujic** [comment]
Hi @gazzar!

That doesn't look right. The poly tool shouldn't care about the `.venv`, but I haven't seen this issue before. I will have a look at it!

**Comment by DavidVujic** [comment]
This error confuses me: is it an error from `Poetry`?

Can you share the structure of your project, and where you have the `.venv`?

**Comment by gazzar** [comment]
Yes, I get that error with any poetry poly <subcommand>, for example poetry poly info. My project structure is

```
.
├── bases
│   └── xfm_stack
│       └── beamline_commandline
│           └── __pycache__
├── components
│   └── xfm_stack
│       ├── beamline_config
│       │   └── __pycache__
│       ├── config_db_api
│       │   └── __pycache__
│       └── devices
│           ├── classes
│           │   └── __pycache__
│           ├── __pycache__
│           └── sim
│               └── __pycache__
├── development
│   └── notebooks
├── projects
│   ├── xfm_beamline_library
│   ├── xfm_jupyter
│   │   └── dist
│   └── xfm_scripts
│       └── dist
└── test
    ├── bases
    │   └── xfm_stack
    │       └── beamline_commandline
    │           └── __pycache__
    └── components
        └── xfm_stack
            ├── beamline_config
            │   └── __pycache__
            ├── config_db_api
            │   └── __pycache__
            ├── devices
            │   └── __pycache__
            └── test_data
```

I had .venv environments under projects/xfm_scripts and projects/xfm_jupyter. Only the xfm_jupyter project includes jupyterlab but even when using the xfm_scripts environment the xfm_jupyter/.venv was causing this error. For now I've deleted the xfm_jupyter/.venv environment in order to proceed. In case it helps, my xfm_jupyter pyproject.toml file is currently

```
[tool.poetry]
name = "xfm_jupyter"
version = "0.1.0"
description = ""
authors = ["Gary Ruben <rubeng@ansto.gov.au>"]
license = ""

packages = [
    {include = "xfm_stack/beamline_commandline", from = "../../bases" },
    {include = "xfm_stack/beamline_config", from = "../../components" },
    {include = "xfm_stack/config_db_api", from = "../../components" },
    {include = "xfm_stack/devices", from = "../../components" },
]

[[tool.poetry.source]]
name = "cachedpypi"
url = "https://pypi.asci.synchrotron.org.au/xfm/dev/+simple"
priority = "primary"

[tool.poetry.dependencies]
python = "~3.11"
as-acquisition-library = {extras = ["standard"], version = "^1.0.1"}
pydantic = "^2.6.4"
typer-slim = "^0.12.3"
pymongo = "^4.7.2"
tabulate = "^0.9.0"
jupyterlab = "^4.2.3"

[tool.poetry.group.dev.dependencies]
ipython = "^8.22.2"
ipykernel = "^6.29.4"
pytest = "^8.1.1"
mongomock = "^4.1.2"

[tool.poetry.scripts]
change-energy = 'xfm_stack.beamline_commandline.change_energy:app'
save-energy = 'xfm_stack.beamline_commandline.save_energy:app'

[tool.pytest.ini_options]
testpaths = ["../.."]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

**Comment by DavidVujic** [comment]
Great, thank you @gazzar!

I think I have found the issue. And it is caused by having `.venv` folders in the local projects. This isn't the expected workflow to have virtual environments in the projects, but I will fix this to make sure the poly tool doesn't traverse any `.venv` folder.

**Comment by DavidVujic** [comment]
@gazzar I have published a new version that should not traverse the subfolders of the projects folder, other than the very first one where the `pyproject.toml` file is expected.

I hope this will solve the issue. Thank you again for reporting this!

**Comment by gazzar** [comment]
@DavidVujic Brilliant! It's late at night here, so I will test this tomorrow my time, but I really appreciate your time and looking into this so quickly! I think you've done a fantastic job with these tools and your documentation is great! I know you say in one of your videos that you recommend doing the development in the development folder, so I guess the expected way would be to maintain a single venv for all projects and to use poly sync then poetry update to keep that up to date. I haven't been doing that, but I could try moving to doing development like that.

**Comment by gazzar** [comment]
Hi @DavidVujic That fixed it! Testing with your new version, I can confirm that it fixes the problem I ran into. Thank you again.
