### ISSUE TITLE
Issue with autogenerated tests and implicit namespace folders for `tdd` theme

### ISSUE THREAD

**Issue by dgot** [DavidVujic/python-polylith#226]
## Describe the bug

When `tdd` is chosen as a theme, polylith will create test folders next to the component source code with the entire namespace structure (which is great). However, when it does this it also creates an `__init__.py` file next to the auto generated test, thus marking the test folder as a module: `<workspace>/components/<component>/test/<namespace>/<component>/__init__.py`

This will make pytest try to load the test and its folder as a module, and ignore the previous implicit namespace folders. If the namespace of this "unwanted" module is clashing with a pre-existing module, like `logging`, pytest will raise an `ImportError` when trying to import the test as a module: 

`ModuleNotFoundError: No module named logging.test_core: logging is not a package`

## Steps To Reproduce

With a `poetry` managed project with the `poetry-polylith-plugin` installed.

1. In a `workspace.toml` and set `tool.polylith.structure.theme="tdd"` and `tool.polylith.namespace="dummy"`
2. Create a `logging` component with `poetry poly create component --name logging`
3. Add `{include = "dummy/logging", from = "components/logging/src"}` to your `pyproject.toml`
4. Install module in your `.venv` with `poetry install`
5. Run `pytest components`

## Error Log
```shell
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
E   ModuleNotFoundError: No module named 'logging.test_core'
```

## Expected behavior

Polylith does not create `__init__.py` files in autogenerated test folders when theme is `tdd`.

## Work Around

Remove `__init__.py` files from test folders manually

## Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Python version: 3.10
 - Poetry version: 1.8.3

**Comment by DavidVujic** [comment]
Thank you @dgot for reporting this issue!

I _think_ this is caused by how pytest does the lookup. Would this configuration solve it?

```toml
[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
```

**Comment by dgot** [comment]
Pytest correctly considers the implicit namespace folders with this configuration 🥳. Thanks for the suggestion.
Yes you are absolutely right, it is more of a folly on `pytests` behalf when doing the lookup, rather than Polylith doing anything "dirty".

Maybe we should add a note regarding pytest and the `tdd` theme under `commands.themes.tdd` [Here](https://davidvujic.github.io/python-polylith-docs/commands/). As it did end up costing me a few hours not understanding what was going on due to pytest's misleading error log.

--------

## Themes

### tdd

The default and will set the structure according to the original Polylith Clojure implementation, such as: components/package/src/namespace/package with a corresponding test folder.

> ⚠️ When using `pytest` with the `tdd` theme, add the following configuration for `pytest`:
> 
> ```toml
> [tool.pytest.ini_options]
> addopts = [
>     "--import-mode=importlib",
> ]
> ```
>
> This is required, as `pytest` will oterhwise not consider the
> implicit namespace folders in the path for the test of your
> brick.
> 
> `pytest` with default configuration will only consider the
> namespace of the last folder where your test is located, if it contains a `__init__.py` file.
> 
> As such, if your brick is named `logging`, this may clash with an already
> existing module, nameply python's `logging`, causing pytest to raise a
> `ModuleNotFoundError`.
>
> This configuration ensures the entire namespace of your brick is
> included when `pytest` does it's test lookup e.g:
>
> - ✅ `<namespace>.<brick_name>.test_core.py` (with configuration)
> - ⛔ `<brick_name>.test_core.py`  (without configuration)
>
> **Example:**
> 
> - ✅ `polylith.logging.test_core.py` (with configuration)
> - ⛔ `logging.test_core.py`  (without configuration)
>

**Comment by DavidVujic** [comment]
Great idea! I'll update the docs!

**Comment by DavidVujic** [comment]
I've updated the `testing` section of the docs, and have added a shorter version of the text you shared. Thank you again! 🙏 👏 

Here's the update:
https://davidvujic.github.io/python-polylith-docs/testing/#running-tests-with-pytest-and-the-tdd-theme
