### ISSUE TITLE
Discrepency between `poly diff` and `poly create` for `tdd` theme

### ISSUE THREAD

**Issue by dgot** [DavidVujic/python-polylith#227]
## Describe the bug

The command `poly diff` assumes the configured `tool.polylith.namespace` is a part of the path to a brick, when trying to determine the changed bricks in `polylith.diff.collect.py::_get_changed_bricks`. However, the namespace is not considered by `poly create` when the theme is `tdd`, and will not be part of the path created.

As such, when using the `poly create` and `poly diff` command together in a polylith workspace with the `tdd` theme, `poly diff` will incorrectly report no changes without the enduser knowing why.

## To Reproduce
1. Set theme to `tdd` in your `workspace.toml`
2. Create component with `poetry poly create component --name dummy`
3. Commit changes and add a tag
6. Make changes to component
7. Run `git diff --stat --name-only` and views changes reported
8. Run `poetry poly diff` and view no changes reported

## Expected behavior

That `poly diff` does not consider `namespace` when the theme is `tdd` OR that the `namespace` is also included by `poly create` when the theme is `tdd`.

Optionally raise an exception by `poly diff` if the expected path to bricks does not exist.

**Desktop (please complete the following information):**
 - OS: Ubuntu `22.04 LTS`
 - Python version: `3.10`
 - Poetry version: `1.8.3`

**Comment by DavidVujic** [comment]
Thank you for reporting @dgot - I think that I've found the issue thanks to your detailed report. 👏

**Comment by DavidVujic** [comment]
I have released new versions of the Poetry plugin (v1.24.0) and the CLI (v1.11.0), aiming to fix this issue when using the TDD theme.

(details in #232)

I hope this solves the issues!

**Comment by dgot** [comment]
This indeed solves the issues.
