### ISSUE TITLE
Getting in touch!

### ISSUE THREAD

**Issue by NellyWhads** [DavidVujic/python-polylith#228]
Hey David!

This is an awesome tool set for managing python monorepos! I'd like to get in touch with some questions regarding usage and maintenance and I've reached out on LinkedIn. Is there a better way to connect?

Hope to link up soon!

**Comment by DavidVujic** [comment]
Hey @NellyWhads, I'm happy that you like Polylith! There's the Discussions section in this repo that I think is a good place for questions and feedback - a good thing with that is also that others with the same kind of questions can join. You can start a conversation there: https://github.com/DavidVujic/python-polylith/discussions

**Comment by DavidVujic** [comment]
(closing this, continuing in the discussions section)
