### ISSUE TITLE
Allow diff from commit hash

### ISSUE THREAD

**Issue by davzucky** [DavidVujic/python-polylith#264]
**Is your feature request related to a problem? Please describe.**
The organization forces us to work with the branches and have four eyes review. We are looking to optimize for branch development testing time and would like to run only tests for modules that have changed since the branch was taken.

**Describe the solution you'd like**
We want to extend the  ```poly diff --since ``` to support hash or short hash as well as tag. 

**Describe alternatives you've considered**
We could create a new parameter named --hash for which we could pass the custom hash.

**Additional context**
This is to optimize branch development on a repository, for which testing is time-consuming.

**Comment by davzucky** [comment]
I am happy to help and contribute, but I haven't looked at the code yet. Let me know if you accept contributions from external people.

If yes, What would be your preference?

**Comment by DavidVujic** [comment]
You are very much welcome to make contributions! For this issue, I have already started working though.

I have added some ideas for contributing here: https://github.com/DavidVujic/python-polylith/blob/main/CONTRIBUTING.md

**Comment by DavidVujic** [comment]
@davzucky I have published new versions of the Poetry plugin (v 1.29.0) and CLI (v 1.17.0). The two `PDM` specific hooks are also updated, because they use one of the changed components.

Please let me know if the new feature works as expected!

**Comment by davzucky** [comment]
Thank you, David. I tested the change, and it works perfectly. Your implementation is really elegant.
Poly cli is missing one command, version to get the version of poly. I had to check my python package to know which version I was running

**Comment by DavidVujic** [comment]
Great!

Yes, that's missing in the tooling. I think I've skipped that because it is already there in the underlying tooling and relatively easy to lookup.

With Poetry, you can check the current plugin version with:
```shell
# displays all installed plugins and versions
poetry self show plugins

# or

poetry self show poetry-polylith-plugin
```

Example, Hatch and uv:
```shell
# uv
uv pip list

# hatch
hatch run pip list
```
