### ISSUE TITLE
Hatch plugin compatibility limit

### ISSUE THREAD

**Issue by NellyWhads** [DavidVujic/python-polylith#284]
I'm attempting to use this with python 3.8 but have run into a version issue. This is sadly a hard requirement for me.

Would it be possible to lower the minimum version here?

https://github.com/DavidVujic/python-polylith/blob/7b0f84f108ef9185512e763546f1a3b64770cc74/projects/hatch_polylith_bricks/pyproject.toml#L24

**Comment by DavidVujic** [comment]
I'll have a look! I have set it to 3.9, but need to double check what the reason was and if it was something Hatch-specific.

**Comment by DavidVujic** [comment]
@NellyWhads I have updated the Hatch hook and it should now allow Python 3.8. Let me know if this works for you or if you run into any issues. I hope you will find Polylith useful!

**Comment by NellyWhads** [comment]
Thank you kindly! I'll test asap
