### ISSUE TITLE
poly diff is not working when structure is not at the root

### ISSUE THREAD

**Issue by davzucky** [DavidVujic/python-polylith#288]
**Describe the bug**
We have a mono repository that contains multiple languages.
The structure look like that

```
|- Python
       |- bases
       |- components
       |- projects
       |- ...
| Javascript
| IaC
| gitlab
| just
```
All Python code is in a folder called "python," which contains the structure of the poly project.

**To Reproduce**
Created a unit test on my branch that shows the problem
https://github.com/davzucky/python-polylith/blob/b2d05174dfc8a6eefa2dd202e7d5a8b89e395552/test/components/polylith/diff/test_collect.py#L53

**Error Log**
Return all the time empty list from the diff

**Expected behavior**
Return the diff since the commit hash change

**Desktop (please complete the following information):**
 - OS: Linux and Mac
 - Python version:  3.12
 - uv version: 0.5.2

**Additional context**

**Comment by DavidVujic** [comment]
Thank you for reporting and adding the unit test @davzucky! ⭐  

I'll have a look, I think I have an idea of why it is not working as expected.

**Comment by davzucky** [comment]
The problem appears in ```collect.py``` in the function ```_get_changed```.

in my case the regex is ```bases/qdev``` however the file name change is ```python/bases/qdev/hawk/common/snapshot_validator.py'```.  I try to add the root in ```_parse_path_pattern```; however, this doesn't solve the problem as this is the full path.
It looks like we need to have the relative path from the git root to the workspace.

**Comment by DavidVujic** [comment]
@davzucky I have published new versions of the Poetry plugin and the CLI. It would be great if you can test and verify things work as expected in your workspace.

Also: thank you for the sponsoring, much appreciated! ⭐ 🙏

**Comment by davzucky** [comment]
Thank you, @DavidVujic. I tested the new version, 1.21, and confirmed it solved the problem. Thank you for your quick turnaround in solving the problem.
