### ISSUE TITLE
Re-write of a module during build doesn't handle f-strings properly

### ISSUE THREAD

**Issue by skrisna** [DavidVujic/python-polylith#309]
**Describe the bug**
I am running `poetry build-project` with the `--with-top-namespace=` option. When the python file is rewritten, it does not handle f-strings properly.

For example, if I have something like:
```python
PYENV_PATH = Path(f'{os.environ["HOME"]}/.pyenv')
```

It gets re-written as:
```python
PYENV_PATH = Path(f'{os.environ['HOME']}/.pyenv')
```

**To Reproduce**
1. Open a terminal window 
2. Go to root of the project
4. Run the command '...'
5. See error

**Error Log**
If applicable, add the error logs.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04
 - Python version: Python 3.10.13
 - Poetry version: poetry-multiproject 1.7.0, poetry-polylith-plugin 1.34.1

**Additional context**

**Comment by DavidVujic** [comment]
Hi @skrisna! Thank you for reporting this issue. I'm not sure that I understand what is going wrong. What is the path that you add in the `--with-top-namespace` option?

**Comment by DavidVujic** [comment]
Oh, sorry. Now I see what you mean. Your code gets rewritten incorrectly, with the `"` and the `'`. I'll have a look, I haven't run into this before.

**Comment by skrisna** [comment]
Yes, that is right- the " gets replaced with '. I had to rewrite my code as 

```python
PYENV_PATH = Path(os.environ["HOME"]).joinpath("/.pyenv")
```

to make it work.

**Comment by DavidVujic** [comment]
I can reproduce the behavor, and I've tried it with Python 3.10 and 3.12. In Python 3.12, the result is valid Python syntax, but not in earlier versions of Python.

The `build-project` is internally using the builtin __AST__ module, and I think that one has a bug with parsing and unparsing f-strings. This is very unfortunate, and I will look into if there is any way to solve it.

Your workaround looks like a good solution, though!

Another way could be:
```python
home_dir = os.environ["HOME"]

PYENV_PATH = Path(f"{home_dir}/.pyenv")
```
I remember having issues with f-strings in general for Python (not related to the `build-project`) before. And that complex f-strings can cause linters and type checkers to report errors. I hope any of the workaround is a good enough solution for you.

**Comment by skrisna** [comment]
Thanks David. Thanks for looking into it. Migrating to 3.12 is a longer project but we will eventually get there. For now, now that I know this is an issue, I would need to scrape our codebase to ensure that this is not a pervasive issue. Thanks!

**Comment by skrisna** [comment]
Closing until I learn more. Thanks again David.
