### ISSUE TITLE
Multiple namespaces?

### ISSUE THREAD

**Issue by bmritz** [DavidVujic/python-polylith#45]
Hello -- thanks for putting together the polylith repo here as a reference. I started to use it for a small project to create a client library around an API, and also create a [singer tap](https://github.com/singer-io/getting-started) for that api. 

One thing I found myself wanting to do is create more than one namespace underneath the `components/` and `bases/` directories. I'm not sure if this is supported or encouraged at this time, both because the `workspace.toml` at the top level looks like it wants a single value for `tool.polylith.namespace`, and if I try to run `poetry poly create workspace --name my_new_namespace --theme loose` again, I get the following error: `[Errno 17] File exists: '/Users/britz/myprojects/simple-garden/bases'`.

Is creating multiple namespaces discouraged? Am I thinking about something the wrong way when I want to be able to do that?

**Comment by DavidVujic** [comment]
Hi @bmritz, great to hear that you are using Polylith! 

Good find, that could be bug 😄 I'll fix it. When I think about it - for Polylith in general, you are encouraged to have one single top namespace, that could be the company name or something that is valid for all artifacts built within an organization. I will do some investigating and return with feedback in this thread!

**Comment by bmritz** [comment]
Thanks David! Yeah as I continued working with it yesterday, I ended up naturally "pushing down" the namespaces I wanted underneath a top level namespace:

So, Instead of doing what I originally asked for and wanted:
```
components/
    namespace_1/
        component_1/
            __init__.py
            core.py
        component_2/
            __init__.py
            core.py            
    namespace_2/
        component_3/
            __init__.py
            core.py
```
I ended up with something like: 
```
components/
    org_name/
        namespace_1/
            component_1/
                __init__.py
                core.py
            component_2/
                __init__.py
                core.py            
        namespace_2/
            component_3/
                __init__.py
                core.py
```

Which, as far as I can tell at the moment, "scratches the itch" I was feeling before. I only need to change the imports slightly (to something like `import org_name.namespace_1.component_1` instead of `import namespace_1.component_1`). In looking at it, I rather like the `org_name` anyway because it is more likely to be universally unique and kind of "addresses" the artifact to the org, as you say. 

Thanks again for the work, I already feel this is an interesting and unique way of organizing python code, and I'm vibing on the principles it is founded on. I look forward to playing around more to see what it gives me.

**Comment by DavidVujic** [comment]
Great! 

It looks like you have created namespaced packages with submodules and that should work quite well with the Polylith architecture. The `poly create` command works out by accident 😆 😅 

I hadn't anticipated that it would be used in this way, but it should definitely support it. I will make sure the other commands behave as expected too with a setup like yours. Thank you for the feedback! ⭐

**Comment by bmritz** [comment]
Ok -- I did find one issue with the `poetry poly create component --name=namespace_2/component_4` hack. Inside the `components/org_name/namespace_2/component_4/__init__.py`, you'll see something like `from org_name.namespace_2/component_4 import core` generated, which isn't valid python.

**Comment by DavidVujic** [comment]
I'll fix this during the week, thank you for reporting! ⭐

**Comment by DavidVujic** [comment]
I have released a new version - v.1.1.1 - that should handle this and create valid Python modules.

Polylith expects the format of having a component-name win a top-namespaced folder, when listing the available components and bases (such as the poly info). But otherwise it should now be valid to type in a name as you have described!

**Comment by bmritz** [comment]
Awesome - thank you very much for adding this in David! I may stay in touch
as I work with it more and have more suggestions and/or questions. Thank
you!
