### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by ann-cooper** [DavidVujic/python-polylith#52]
This is a great project @DavidVujic! I don't have a feature request, it's more of a question: would you be open to contributions to the unit tests?

**Comment by DavidVujic** [comment]
Oh, yes please! 😄 

If you want to help out with this, I would love to have the structure according to the `loose` theme.

Basically, the brick tests in a structure like this: `test/{brick}/polylith/{package}`

Don't hesitate to reach out if you think I can help out with something or if you find things that seems weird.

**Comment by ann-cooper** [comment]
I'm not sure I follow entirely what the test file path should look like, so to check: if I were to write a test for the function create_project_toml in components/polylith/project/create.py, then the test path would be something like:
test/components/polylith/project/create/tests.py ?

**Comment by DavidVujic** [comment]
How about something like this?

Example, testing the code in the `project` component:
 ```
test/
  components/
     polylith/
       project/
          test_create.py
          test_parser.py
          ...
```

If a component or base is small and it feels like too much to split it, it will probably make sense to have one test-file for all modules in there.

**Comment by ann-cooper** [comment]
That works for me!

**Comment by ann-cooper** [comment]
I created a new branch with my first test, but I don't have permission to push -- how would you like to handle that?

**Comment by DavidVujic** [comment]
Do you mean permissions to this repo? I think that you should fork it to your own space, there you can create branches and also make Pull Requests to this repo.

**Comment by DavidVujic** [comment]
Here's a GitHub guide that might help out: https://docs.github.com/en/get-started/quickstart/contributing-to-projects
