### ISSUE TITLE
Libs command is not working as expected

### ISSUE THREAD

**Issue by tomsej** [DavidVujic/python-polylith#57]
**Describe the bug**
Hi David, I apologize for late answer. I am truly excited about the new feature of lib validation. I have just been playing with it, and it is magical, but I have some problems with it:
- if I am not mistaken, the lib command is comparing bricks dependencies with a root `poetry.lock`. I would expect to compare it to a project's `poetry.lock`. Think you can have third-party dependency in the root `pyproject.toml`, but not in the project's `pyproject.toml` -> built artefact does not contain all the required dependencies.
- unfortunately, it is not working with Poetry custom dependency groups. https://python-poetry.org/docs/master/managing-dependencies/#adding-a-dependency-to-a-group. The reason is probably this filter https://github.com/DavidVujic/python-polylith/blob/27c451e704f1e09f314fa6dfc51396d7ced4dc45/components/polylith/poetry/commands/libs.py#L31. Seems that Poetry is setting `category = "dev"` if you add dependency to a group. Those groups should be most likely used for development, but they are really practical with a polylith since you do not have to always install all the dependencies.

**To Reproduce**
1. In **python-polylith-example** run `poetry remove fastapi`.
2. `poetry poly libs` is reporting that `fastapi` is missing, even though it is present in `projects/my_fastapi_project/poetry.lock`
4. Run the command `poetry add fastapi --group fastapi`
5. `poetry poly libs` is still reporting missing `fastapi`.

**Expected behavior**
See a description.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Python version: 3.11.2
 - Poetry version: 1.3.2

**Comment by DavidVujic** [comment]
Thank you for trying out and sharing feedback!

Yes, by just running `poetry poly libs` from the root folder in the workspace will use the lock-file from the root. But if you use the `--directory` flag with the path to a project, it should behave as expected.

I'm planning to do this in a better way when running the command for all projects in the workspace, to avoid the confusion between which `poetry.lock` file actually is used.

Good catch with the categories! I took a shortcut and figured the "main" was good enough, but now I know better and how it is used! 😄 I'll have a look at that one.

**Comment by tomsej** [comment]
Oh, I see! Yeah, it works fine with a `--directory` flag! Cool. I just found another small bug. Seems that some libraries have slashes in the package name (like `aws-lambda-powertools`) but of course, in import statement they use underscore (like `aws_lambda_powertools`). Command is then falsely reporting that that library is missing. It would also be great to have some option to exclude some libraries. I know i'm annoying :D

**Comment by DavidVujic** [comment]
I really appreciate this!

I'm thinking about normalizing the names before comparing what is used and what is installed: treating dash and underscore in names as equal. What do you think about that?

**Comment by tomsej** [comment]
Yeah, that makes a lot of sense to normalize it. Thanks

**Comment by DavidVujic** [comment]
I have published a new version, that hopefully fixes these issues 🤞 

One tradeoff I went for is that the library lookup now will collect dependencies from all groups, and the command won't notice if the production code would by accident import a library from the dev-dependencies.
