### ISSUE TITLE
Can't trace an exception 

### ISSUE THREAD

**Issue by betterthanever2** [DavidVujic/python-polylith#73]
**Describe the bug**
Whenever I run `poetry poly libs`, or `poetry poly check` I get this error: `'charmap' codec can't decode byte 0x98 in position 880: character maps to <undefined>`
I have no idea what is wrong and where to look.

**To Reproduce**
I'm not sure this is reproducible.

**Expected behavior**
A more detailed description of the error, preferably with indication of which file is faulting.

**Desktop (please complete the following information):**
 - OS: Win10
 - Python version: 3.10.5
 - Poetry version: 1.3.2

**Additional context**
Just moved a multifaceted project to polylith structure, and for starters assigned everything to one `project` . I started moving things around (that is, creating new bases/components and moving code there from legacy ones, then removing legacy ones). This wasn't happening at the beginning.

**Comment by DavidVujic** [comment]
Thank you for reporting @betterthanever2!

It looks like the commands have run into unexpected encodings in one or more files. I think I might have missed out in explicitly specifying the encoding when analyzing files (as done in the `check` and `libs` commands).

I'll look into this right away!

**Comment by betterthanever2** [comment]
Thank you! Love this software, btw

**Comment by DavidVujic** [comment]
There's a new version out: 1.5.0

I have added some file opening guards that I hope will solve your issues! The bump includes a new feature too (that is why it is 1.5.0): including the development project in poly info and libs.

Please try it out and let me know if it works 🙏

**Comment by betterthanever2** [comment]
@DavidVujic quick question: how do I update the plugin? Pardon me if it's stupid, but I haven't found it in the docs.

**Comment by DavidVujic** [comment]
A very good question! The Poetry docs doesn't seem to describe that.

I usually remove, and then add again:

```
poetry self remove poetry-polylith-plugin

poetry self add poetry-polylith-plugin@latest
```

**Comment by betterthanever2** [comment]
Thank you! Updating to 1.5.0 went fine, and I no longer get the error I was getting. I'm a little confused by the output, though. Take a look at a screenshot. Judging by the different number of reported missing packages in the 2 blocks (what's up with that, btw?), something may have been duplicated.
![4OxJKTk7Vr](https://user-images.githubusercontent.com/68774738/228339413-13324798-7883-437e-8de4-216147f4efb9.png)

**Comment by DavidVujic** [comment]
And, if possible, could you share the contents of the `pyproject.toml` file? Unless it is an in-house project that is not allowed to expose in public.

**Comment by betterthanever2** [comment]
Yes, there is just one `project`. And here's the file structure:
![image](https://user-images.githubusercontent.com/68774738/228341947-61f3f38e-6acf-4514-bf42-34da797da573.png)

**Comment by DavidVujic** [comment]
Thank you! Looks good! Can I have a look at the one in the projects folder too?

**Comment by betterthanever2** [comment]
[Not much different](https://gist.github.com/betterthanever2/7ae853f73c60e3ea43dc3633e2bbafe8)...

**Comment by DavidVujic** [comment]
May I ask for a look in the `workspace.toml` too? Just to make sure.

**Comment by betterthanever2** [comment]
I'm not sure. It was either added automatically, or I may have copied it over from one of the 2 example projects I looked into

**Comment by betterthanever2** [comment]
```
[tool.polylith]
namespace = "wapaganda"
git_tag_pattern = "stable-*"

[tool.polylith.structure]
theme = "loose"

[tool.polylith.resources]
brick_docs_enabled = true

[tool.polylith.test]
enabled = false
```
Note: test was "disabled" already after the setup

**Comment by DavidVujic** [comment]
No, you shouldn't need that. It looks like a declaration used when you actually build a plugin of your own.

**Comment by DavidVujic** [comment]
What is the output when you run the Poetry built in command `poetry show`?

**Comment by betterthanever2** [comment]
> No, you shouldn't need that. It looks like a declaration used when you actually build a plugin of your own.

It's declared in project-level file in this repo 🤦 Overkill 😄

**Comment by betterthanever2** [comment]
> What is the output when you run the Poetry built in command `poetry show`?

When I run `poetry show` I get a really long list of libraries

**Comment by DavidVujic** [comment]
1. I think the `poly libs` feature is a bit too naive when it tries to figure out if a library is installed or not. If the name in the list of dependencies is too different from the one used in the python code, it will end up in the "could not locate" list. I'll see if I can do some better comparisons than what is done today. For now, see it as a guide (that might be wrong).

2. I cannot figure out why the screenshot looks weird. It should have had a header `Libraries summary for development` there.

**Comment by DavidVujic** [comment]
One thing that comes to mind: how does the `snapshot` base import wapatools and others`

**Comment by betterthanever2** [comment]
>     2. I cannot figure out why the screenshot looks weird. It should have had a header `Libraries summary for development` there.

This is indeed weird. It may be related to some terminal bug. Another thing that happened on that front is that when I enlarged the terminal window, the whole 2nd section of the output disappeared.

**Comment by betterthanever2** [comment]
> One thing that comes to mind: how does the `snapshot` base import wapatools and others?

As entire scripts
![image](https://user-images.githubusercontent.com/68774738/228349251-912d72f9-97dc-4023-a01a-641c464fb345.png)

**Comment by DavidVujic** [comment]
Thanks! Looks good. According to the screenshot, the snapshot base imports something called `py7zr` is that correct, or is the poly libs summary wrong there?

**Comment by betterthanever2** [comment]
> Thanks! Looks good. According to the screenshot, the snapshot base imports something called `py7zr` is that correct, or is the poly libs summary wrong there?

It is correct. This dependency is also actually missing from the `pyproject.toml`

**Comment by betterthanever2** [comment]
`loaders` and `pyyoutube` are aliases of `python-loaders` and `python-youtube` respectively

**Comment by DavidVujic** [comment]
Ok! So the tool seems to have gotten some missing dependencies reported right. The aliases is making the tool miss them, and that's a bug.

Is there anywhere in the python code where the imports for wapatools isn't `from wapatools` or `import wapatools`?

**Comment by betterthanever2** [comment]
> Sorry, not wapatools, but wapaganda!

There were (it's legacy residue). I corrected almost all, but may have missed something
Also: it would've been really nice to see where the missing dependency is used. For example, there is a `supaword` package, among other things, and it's just the old name of this one, and it shouldn't be there.

**Comment by DavidVujic** [comment]
Thank you for helping out with this, and I appreciate your patience with the polylith tool! 😄 

There's a couple of bugs we already have identified that I will add as issues and work on:
* terminal weirdness with double screens (looks like PowerShell)
* too naive library comparison, such as python-youtube vs pyyoutube

The rest is a bit difficult to find out for now. If it would be ok for you I could have a closer look in the code in a zoom-call or similar, or if I could have access to the repo (I totally understand if that is not possible, just a suggestion).

**Comment by betterthanever2** [comment]
> Thank you for helping out with this, and I appreciate your patience with the polylith tool! 😄
> 
> There's a couple of bugs we already have identified that I will add as issues and work on:
> 
>     * terminal weirdness with double screens (looks like PowerShell)
> 
>     * too naive library comparison, such as python-youtube vs pyyoutube
> 
> 
> The rest is a bit difficult to find out for now. If it would be ok for you I could have a closer look in the code in a zoom-call or similar later this week or any other time, or if I could have access to the repo (I totally understand if that is not possible, just a suggestion).

Wow, you're really going heavy on this. I appreciate it. Let me sleep on the code exposure thing, tough. 

As for the patience - really not much was required. Sure, I got confused here and there, like it happens every time I learn something new, but it was comparatively easy to resolve in each case. I think, this is in part, due to easy-to-grasp architecture, and in part, - to the really great documentation you have. Thanks for that - saves time, reduces frustration.

**Comment by betterthanever2** [comment]
@DavidVujic we can do a zoom call, if you don't mind me asking questions about polylith

**Comment by DavidVujic** [comment]
Great! Of course, questions are welcome 😄

**Comment by betterthanever2** [comment]
Not sure how to connect. Here's my [email](https://privnote.com/tcynYU5i#TeugtoB5Y)

**Comment by DavidVujic** [comment]
I'll close this one, added new Github issues:

#76 
#77
